### PR TITLE
Fix #138 & #137 - Non-backup are not returned

### LINKED ISSUE #138: Issue with dbrestore
So i just updated dbbackup from version `2.0.4` to version `2.3.2` so i could get the no `--noinput` (https://github.com/django-dbbackup/django-dbbackup/pull/99) option when i `dbrestore` but i am running into this issue:

```
root@f0c2e40cdef6:/vagrant# python manage.py dbrestore --noinput --settings=xxx.settings.local
Restoring backup for database: postgres
Finding latest backup
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/dbbackup/management/commands/dbrestore.py", line 58, in handle
    self.restore_backup()
  File "/usr/local/lib/python2.7/dist-packages/dbbackup/management/commands/dbrestore.py", line 82, in restore_backup
    compressed=self.uncompress)
  File "/usr/local/lib/python2.7/dist-packages/dbbackup/storage/base.py", line 148, in get_latest_backup
    return max(files, key=utils.filename_to_date)
  File "/usr/local/lib/python2.7/dist-packages/dbbackup/utils.py", line 373, in filename_to_date
    datestring = filename_to_datestring(filename, datefmt)
  File "/usr/local/lib/python2.7/dist-packages/dbbackup/utils.py", line 358, in filename_to_datestring
    return search.groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'

```

Any ideas? Last time i tested this was with the master at the time

### PR DESCRIPTION
**Pull request by ZuluPro**
Created from @benred42 branch (PR #130).
I made some improvements on it.

I fix issues #138 and #137.
Now file without date are not considered as backup, so won't be listed.

I also began to add Shell functional test in ``tests/functional.sh`,
I'll add counter check later.

### CODE REVIEW

**Comment by ZuluPro** [comment]
@benjaoming @mjs7231 @psychok7 @ManuelGysin:
What do you think about ? Could you test before merge

**Comment by benjaoming** [comment]
These look like great changes!

Maybe you should superseed this PR by another one just to get the coverage improvements? :)

**Comment by psychok7** [comment]
I can test this on Monday

**Comment by ManuelGysin** [comment]
These patches will not throw any errors but no backups are found.

**Comment by benjaoming** [comment]
Maybe this part is problematic since if no files are found, it will still succeed?

```
         files = self.storage.list_backups(content_type='media')
-        self.assertEqual(8, len(files))
+        # self.assertEqual(8, len(files))
         for file in files:
             self.assertIn('.media', file)
```

**Comment by ZuluPro** [comment]
@benjaoming: I commented out it because I'm not sure how many files I will have. But I'll update it for test ``len(files) > 1``.

**Comment by psychok7** [comment]
ok so i tested this (dbbackup and dbrestore) and it seems to have fixed https://github.com/django-dbbackup/django-dbbackup/issues/138

Will you be releasing another version on pypi with this patch anytime soon @ZuluPro ?

**Comment by ZuluPro** [comment]
@psychok7 : Yep as soon as possible, I want to be sure to fix issue #137

**Comment by ManuelGysin** [comment]
Sorry my bad, somehow I got a very, very old django-storage-redux version over pip. I have no idea why, no everything works with this patch set.

**Pull request merged**
