### PR TITLE
Remote azure storage

### PR DESCRIPTION
**Pull request by dorianamouroux**
I create an Azure Storage class Adapter for remote storage.
I'm using a third party library for the actual Storage system.
I documented the options.
The library for azure storage has a small glitch in it, making `listbackups` command impossible. I fix it and submitted a PR to it, I think it should be merge soon.

Cheers !

### CODE REVIEW

**Comment by ZuluPro** [comment]
Hello @dorianamouroux,
Thanks a lot for this contribution.

We are developing DBbackup 3 and in this version we'll drop support for storages. As Django already have a great storage API and its third apps (like `azure_storage`), we want to focus only backup and restore mechanisms.

Your contribution could be interesting as a snippets on documentation because it demonstrates how to use a third part storage with DBBackup.

What do you think about ?

**Comment by dorianamouroux** [comment]
I think it's too bad that we drop support for storage.
For projects that use DBBackup, it's really convenient to have storage options.
We can use different configurations for backup files and media files without having to hack anything (and have a cleaner codebase).
I understand the idea behind it, maybe split off the backup and storage part would be a good solution.

Though you can use my code as snippets for documentation if you don't keep it for storage system 👍

**Comment by ZuluPro** [comment]
@dorianamouroux 
I like your idea of make a separate repo for storage but my problem is the time used for support this.
@benjaoming @mjs7231 What do you think about ?

**Comment by dorianamouroux** [comment]
I can give some of my time for it, I like the project.

**Comment by ZuluPro** [comment]
@dorianamouroux : If you have some time and some $ on Azure, could I suggest you to contribute to [django-storages Azure backend](https://github.com/jschneier/django-storages/issues/170) ?

I would like to be sure it work's with DBBackup.

**Comment by dorianamouroux** [comment]
`django-storages` is really outdated and looks barely maintained anymore. The Azure Backend they offer is missing all required features we expect for a storage backend, it does only work for `collectstatic` (and --clear doesn't work). Also, you cannot pass parameters to the constructor thus you cannot give different parameters for backups and normal mode. They doesn't seems to be very responsive to contribution neither.
  
I used this storage backend https://github.com/Rediker-Software/django-azure-storage there is no documentation, but I managed to make it works for backups (with a PR). There is still work to do on this package because I cannot list the different backups. I might write my own Azure Backend.

**Comment by ZuluPro** [comment]
Hello @dorianamouroux 
What about this storage ?

**Comment by ZuluPro** [comment]
Django DBBackup doesn't contains object storage anymore.
This issue is no more relevant.

**Pull request closed without merging**
