### PR TITLE
fix problem with empty media tarball name and boto3 s3 storage

### PR DESCRIPTION
**Pull request by pacahon**
I've switched to new boto3 s3 storage implementation from `django-storages` and realized, that it doesn't work due to empty tarball name. This PR should fix it. Maybe it's relevant to `dbbackup` cmd also.

### CODE REVIEW

**Comment by ZuluPro** [comment]
Hello @pacahon,
Thank you very much for your work.
Maybe the comments are useless, did you test with other storages ?

**Comment by pacahon** [comment]
@ZuluPro Now I'm not sure it's the right place to fix unpredictable behavior. 
More it looks like hack, because django's File.name attribute is `The name of the file including the relative path from MEDIA_ROOT.`

Django storage save method accepts any file-like object https://code.djangoproject.com/ticket/27145, so all should be ok from our side. But bug is still here. Maybe it can be fixed in Django later https://code.djangoproject.com/ticket/27150#ticket but should investigate the problem deeply first.

I can try to send patch to `django-storages` first, but really not sure how fast they can reply.

**Comment by ZuluPro** [comment]
@pacahon: Try to send a patch, I am also maintener of Django-Storage...

**Comment by pacahon** [comment]
@ZuluPro Ok, I'll try! :) Saw you in contributors, but didn't realize you can merge PR too. 
Mb any thoughts on https://github.com/jschneier/django-storages/issues/194 ?

**Comment by ZuluPro** [comment]
Hello @pacahon 
Is this issue is still relevant ?

**Comment by ZuluPro** [comment]
@pacahon Any news ?

**Comment by pacahon** [comment]
Sorry, but I can't remember in what case I had this problem. Since this PR wasn't merged, but I'm still using dbbackup, I definitely did something with this issue (maybe only on my side)

**Pull request closed without merging**
