### PR TITLE
Allow for custom engine in DATABASES setting

### PR DESCRIPTION
**Pull request by skyl**
I believe this change will allow for custom db backend engine.

### CODE REVIEW

**Comment by skyl** [comment]
Hi, thanks for publishing this project. This patch is working for me in production now if you want to merge it. I have a custom database backend so it will never be in your mapping ...

Thanks!

**Comment by ZuluPro** [comment]
@skyl But why this patch, if you can extend `CONNECTOR_MAPPING` with `CUSTOM_CONNECTOR_MAPPING` ?

**Comment by ZuluPro** [comment]
@skyl Any news ?

**Comment by jonathan-s** [comment]
@skyl It's already described here when you use a custom engine -> https://django-dbbackup.readthedocs.io/en/master/databases.html?highlight=DBBACKUP_CONNECTORS#database-settings 

Or was this explanation confusing?

**Pull request closed without merging**
