### PR TITLE
Add ability to tack on extra arguments to backup command.

### PR DESCRIPTION
**Pull request by willson556**
Useful for excluding certain tables or other small backup tweaks.

### CODE REVIEW

**Comment by benjaoming** [comment]
Cool - but would the same logic not also apply to the restore command? :)

**Comment by willson556** [comment]
Agreed :)

**Comment by benjaoming** [comment]
Looks good, @ZuluPro what's your take?

**Comment by ZuluPro** [comment]
@willson556 
Thank you very much for your contribution, and sorry for my latency.

@benjaoming 
I'm not against, but be really think about remake the DBCommand system (issue #102).

**Comment by benjaoming** [comment]
@ZuluPro since #165 was merged, should this be closed and are OPs original motives fulfilled in #165?

**Comment by ZuluPro** [comment]
Hello @willson556 : Coud you say us if DBBackup master version, do what you want ?

**Pull request closed without merging**
