### PR TITLE
Quick fix for proper selection of DB name to restore

### PR DESCRIPTION
**Pull request by adi-**
Currently database 'default' is hardcoded

### CODE REVIEW

**Comment by ZuluPro** [comment]
Hello @adi- ,
Could you:
- Fix the mongo failing test ? (Maybe just add a connection in test settings)
- And perhaps add a unit tests for your use case ?

**Comment by ZuluPro** [comment]
@adi- If you have problems with MongoDB, say me ;)

**Comment by adi-** [comment]
Haven't tried yet. Have no time recently :(

**Comment by ZuluPro** [comment]
@adi- Like everyone else ;)
I'll try to touch it this week-end.

**Comment by turacosianritesh** [comment]
Hi zulupro, Can you please merge this PR, it fixes the db selection correctly for dbrestore,

**Pull request merged**
