### PR TITLE
Add missing variables to settings.

### PR DESCRIPTION
**Pull request by balavec**
When I tried to restore the backup that was created it was not getting the right one.

### CODE REVIEW

**Comment by ZuluPro** [comment]
Can you add a test for confirm that's work ?
Or add an issue for it ?

**Comment by benjaoming** [comment]
I don't think this is a cause of errors in the current master branch.

Only occurrences are here:

https://github.com/django-dbbackup/django-dbbackup/blob/master/dbbackup/dbcommands.py#L51
https://github.com/django-dbbackup/django-dbbackup/blob/master/dbbackup/dbcommands.py#L82
https://github.com/django-dbbackup/django-dbbackup/blob/master/dbbackup/dbcommands.py#L166

All of them use getattr... but the fix is nice, you should just *remove* getattr in the above mentioned, otherwise it's sort of repeating the same pattern two different places.

**Comment by balavec** [comment]
The reason for doing this was because I was testing the creation of backup and doing a restore after that.
I have a MySQL database and the backup created had a 'mysql' extension. When I tried to restore it it could not find the backup. So I started looking for an error and figured out that the code was only looking for a 'backup' extension.
To keep the pattern of the code i added the 3 lines. I admit it is not the most elegant but it is reading the constants from the same file as BACKUP_DIRECTORY.

**Comment by balavec** [comment]
To be clear: there were no error when I was running the backup or restore.
The problem was that it was not picking up the right extension.

**Comment by benjaoming** [comment]
@balavec are you running from the master branch or a release?

**Comment by balavec** [comment]
@benjaoming I was running from a release. Thanks for reminding me.

**Comment by benjaoming** [comment]
I honestly don't think this issue is valid on current master, @balavec could you try that instead?

**Comment by balavec** [comment]
I think you are right. I will cancel the pull request.

**Comment by benjaoming** [comment]
Alright, cool, but thanks for caring :)

**Pull request closed without merging**
